### ISSUE TITLE
Clarify Licenses

### ISSUE THREAD

**Issue by cramertj** [remram44/adler32-rs#7]
The [Cargo.toml](https://github.com/remram44/adler32-rs/blob/master/Cargo.toml#L10) says this crate is BSD-3-Clause, but the [LICENSE](https://github.com/remram44/adler32-rs/blob/master/LICENSE) included is the MIT license, and the text of the library [includes the zlib license](https://github.com/remram44/adler32-rs/blob/master/src/lib.rs#L20).

Can you clarify this situation? Do all three licenses apply to the crate?
cc @jamesr

**Comment by remram44** [comment]
The zlib license is included along with the code that I translated directly from the zlib C source code.

The discrepancy is from when I pulled the lib out of the [rs-sync repo](https://github.com/remram44/rs-sync), I will fix ASAP. Thanks for reporting!

**Comment by remram44** [comment]
The intent was always for this to be BSD, and you may use any version as such. The MIT LICENSE file was copied by mistake from rs-sync.

**Comment by remram44** [comment]
Updated LICENSE file with 4ebae36dd16e16ef7bbbdde72dbb5fd8f72b5b8f.

I hope that fixes your issue!

**Comment by jamesr** [comment]
Thanks @remram44, that helps.  There's still a copy of the zlib license and zlib source code in https://github.com/remram44/adler32-rs/blob/master/src/lib.rs#L16 and users of this crate likely need to adhere to the terms of this license as well in order to use this code.  Could you place a copy of this license text at the top level of the repository and note that its terms apply in the Cargo.toml?  Thanks!

**Comment by remram44** [comment]
To the best of my knowledge zlib is compatible with BSD, so I am allowed to redistribute it under BSD license. The LICENSE file is not the best place for provenance details, since it is not shown on crates.io. Acknowledgement of the authors of the original C code can be added, but if I just put them as authors in `Cargo.toml` I might be breaking clause 2?

**Comment by jamesr** [comment]
I think license compatibility is a separate issue.  My issue is that when using this library in the context of a larger program, I need to compute the set of licenses, terms, conditions, etc that apply to all parts of that program.  For this crate, that includes the BSD license noted in the metadata and top-level LICENSE file as well as the zlib license for the code in src/lib.rs in this crate.  When that license text is included only in a comment in a source file within the crate, that makes this job more difficult.  Having all of the license text and terms that apply to the crate clearly marked at the top level of the repository and annotated correctly in the metadata would make this job much easier.

I'm not as familiar with the conventions of the Cargo metadata, but if there's a way to mark that different license terms apply to different portions of the library that'd be ideal.  Failing that, describing the situation clearly in the README.md file would probably do the trick and show up in crates.io.

Thanks.

**Comment by remram44** [comment]
There is no requirement on you when you use this library. The only requirement is that this single notice is kept in this location in source distributions of this crate. I can update the README.md to state that it is based off of zlib code authored by Jean-Loup Gailly and Mark Adler, however it might be too much information to add to Cargo.toml's package.description (though crates.io renders the README now, so it would show there already).

**Comment by remram44** [comment]
Let me know if I'm wrong about any of this, IANAL. I would rather not impose additional requirements on all users of this crate if they are not required.

I suppose I could relicense the whole thing as zlib and be done with it. The BSD licensing was for rs-sync.

**Comment by jamesr** [comment]
I am also not a lawyer, but am advised that we are required to provide notice when providing software under the zlib license.  Since this crate includes code from zlib this means that we would like to provide notice when using this crate.  That is difficult for us to do when the zlib license text is only in a comment, so I'd like to make it easier.  Having a LICENSE-ZLIB file or similar in the top level of the repository along with text in README.md indicating which parts this license applies to would work for me.

Since I am not a lawyer (and not your lawyer) I can't provide any conclusion about whether this notice requirement applies to you or anyone else using this crate.

**Comment by remram44** [comment]
I can make those changes for you! Do I need to release a new version on crates.io? 🤔

**Comment by jamesr** [comment]
Yay, thanks so much!  We import from crates.io so if you could publish a new version once those changes are in we'd greatly appreciate it.

**Comment by remram44** [comment]
I just made the whole thing zlib after more licensing issues arose (413c6138).
